### ISSUE TITLE
Clone markers inside complexes

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#127]
Is there any possibility that inside a complex an EPN will be cloned? If not, then we could clearify this in the spec (clone makers can not be used inside complexes).

Reported by: falkschreiber

**Comment by adrienrougny** [comment]
In the spec it is specified that clone markers  are for EPNs, and subunits are not EPNs, hence I do not think it is needed to specify explicitly that subunits cannot be cloned.

**Comment by hasanbalci** [comment]
> In the spec it is specified that clone markers are for EPNs, and subunits are not EPNs, hence I do not think it is needed to specify explicitly that subunits cannot be cloned.

I agree with this statement. In section 2.3.3 Glyphs: Clone markers, it says 'If an EPN is duplicated on a map, it is necessary to indicate this fact by using the clone marker auxiliary unit.' and only mentions about EPNs. In section 2.3.4 Glyphs: Subunits, it says 'Subunits do not represent or mimic entity pools.' Hence, I don't think any additional explanation is needed.

**Comment by draeger** [comment]
Actually, the concept of clone markers is problematic and should be abandoned or changed entirely for the following reasons:

1. These markers always highlight exactly the wrong parts of the network. In a large-scale, realistic network, we expect many currency metabolites, such as ATP or NADPH, and so forth. So, it is hard to keep track of the primary metabolites. Clone markers, however, highlight the distracting secondary metabolites.
2. Their shape is inappropriate because they fill part of the node, making it difficult to overlay SBGN maps with measurement data. If you want to display any quantity, e.g., the concentration of some metabolite, you should remove the clone marker if it conflicts with the visualization.
3. They are not universally applicable, as this discussion indicates: The current specification does not allow clone markers for some glyphs.

I suggest rethinking this concept and considering removing it entirely or highlighting those glyphs that are not cloned rather than those that are cloned.

**Comment by adrienrougny** [comment]
I think I agree with Andreas, clone markers could be abandoned in a next level of PD.
@draeger If there is not already an issue for this, would you be willing to make one, with all the arguments you provide?

**Comment by hasanbalci** [comment]
To clarify that subunits cannot be cloned, I updated the statement in Section 2.3.4 Glyphs: Subunits as "Subunits do not represent or mimic entity pools (Section 2.4)**, so they cannot be cloned** and may only be used to represent the subunits included in a complex."
