### ISSUE TITLE
Unspecified stoichiometry

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#146]
The spec says that a ? can be used to represent unspecified stoichiometry. This conflicts with fact that cardinality is always defined for an EPN and the stoichiometric process should be balanced. The unspecified conflicts with this and should be removed from V2.0 of the spec.

Reported by: stumoodie

**Comment by adrienrougny** [comment]
One solution is to change "required" to a should in section 2.7.1 about undefined stoichiometry.

This label is a number **or a "?" character** enclosed in a rectangular container with one of the long sides adjacent to the consumption arc. The cardinality **should be used to** to eliminate ambiguity when the exact composition, or the number of copies, of the inputs or outputs to a reaction are ambiguous from the map.

**Comment by draeger** [comment]
As far as storing in SBGN-ML goes, one could represent the `?` with the actual numerical value `NaN`, so that the data type is always a number but renders as a question mark if not-a-number is given.

Next, I also believe it should be possible to use SBGN to draw ideas of how processes might take place or to express knowledge gaps. Imagine, you could only save a valid Word file if all words in it are correctly spelled and all senteces end with a full stop…

**Comment by adrienrougny** [comment]
@draeger Added your comment on NaN as an issue in the lisbgn repo
