### ISSUE TITLE
Integrate the new requirements for state variables labels ? (p.50-51). Value is represented by a non-empty optional string, same for the variable. Deprecate the representation of the variable outside of the box?

### ISSUE THREAD

**Issue by adrienrougny** [sbgn/process-descriptions#183]

**Comment by hasanbalci** [comment]
Does this issue refer to Section 2.3.2 Glyph: State variable or somewhere else (because p.50-51 refers to Syntax and Semantic Rules)? In Section 2.3.2, the current text in Label emphasizes the deprecation of displaying name outside the shape. The current text for the value and name of the state variable in the document is as follows:  

`The label is constituted of two substrings separated by the character “@”, the first one indentifying the value of the state variable, and the second one its name. The character “@” is omitted when the state variable is unnamed.`
