### ISSUE TITLE
Vector versus Set? 

### ISSUE THREAD

**Issue by cannin** [sbgn/process-descriptions#222]
How to define the vector? We need an order (otherwise its only a set)

**Comment by cannin** [comment]
Changed

**Comment by Adrienrougny** [comment]
How was it changed? I still see "set of all its state variables".

**Comment by cannin** [comment]
I changed the words vector to set. I thought that the problem was that the state variables are not actually ordered therefore the word set was more appropriate than vector?

**Comment by Adrienrougny** [comment]
Oh, ok. I thought the original was the "set" version.
I think that for now, we should keep the "vector" version, and that we should define an order (in section 3).
Indeed, if we consider that an EPN's state values are used to define its identity (as stated in legend of Table 3.1: "The term state values indicates that the values of all the EPN’s state variables are used in the definition of its identity."), having sets of state values is not possible. Having vectors solves the issue. As for the order, we could for example define it based on the angular positions of the state variables on the border of the macromolecule (this position is for example used in CellDesigner to place them).

Defining a right way to model state variables at the conceptual level looks tricky. For me, the current way is not perfect and should be changed in the future (for example, it makes impossible to merge maps. I would like the conceptual model of PD to make it possible), but I think that for now this way is sufficient to define how to clone macromolecules.

**Comment by Adrienrougny** [comment]
Sorry, I was not clear.
I was just suggesting to keep the term "vector", and, because as you said, a vector is ordered, to specify in section 3, that the vectors should be ordered in a consistent way for different glyphs (actually, for those that share the same label). We would just have to add one sentence in section 3. The stuff about angles was just an example of consistent ordering. This would have no impact on the way maps are represented, software implementation or on anything else but the conceptual model of section 3.

**Comment by cannin** [comment]
* "set" should be changed to "list" in L1V2.1 
* Any additional rules on ordering state variables with no variables should be postponed to L2+

**Comment by hasanbalci** [comment]
I replaced all "the set of all its state variables" by "the list of all its state variables". These changes are in Sections 2.3.4, 2.4.3, 2.4.4 and 2.4.5.
